In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 8.6 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [36]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-03-17 10:02:06,456] A new study created in memory with name: no-name-89a15aba-af04-4a1a-add9-15acbb59634c
[I 2026-03-17 10:02:06,935] Trial 0 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 80, 'max_depth': 9}. Best is trial 0 with value: 0.7597765363128491.
[I 2026-03-17 10:02:08,109] Trial 1 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 197, 'max_depth': 18}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:09,144] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 187, 'max_depth': 4}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:10,294] Trial 3 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 200, 'max_depth': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:11,397] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 185, 'max_depth': 15}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:12,586] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 188, 'max_depth': 20}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:13,559] Trial 6 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 171, 'max_depth': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:14,004] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 77, 'max_depth': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:15,139] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 183, 'max_depth': 15}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:15,668] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 83, 'max_depth': 15}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:16,872] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 20}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:18,376] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 149, 'max_depth': 20}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:19,199] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 110, 'max_depth': 18}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:20,159] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 158, 'max_depth': 17}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:20,938] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 123, 'max_depth': 13}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:21,910] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 166, 'max_depth': 11}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:23,083] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 18}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:23,728] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:24,557] Trial 18 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 137, 'max_depth': 17}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:24,904] Trial 19 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 53, 'max_depth': 12}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:25,930] Trial 20 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 173, 'max_depth': 10}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:26,751] Trial 21 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 133, 'max_depth': 17}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:27,656] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 146, 'max_depth': 18}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-03-17 10:02:28,429] Trial 23 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 127, 'max_depth': 16}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:29,359] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 122, 'max_depth': 14}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:30,302] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 101, 'max_depth': 16}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:31,390] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 113, 'max_depth': 13}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:32,266] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 17}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:32,626] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 19}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:33,174] Trial 29 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 92, 'max_depth': 8}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:34,072] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 16}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:34,472] Trial 31 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 19}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-03-17 10:02:34,889] Trial 32 finished with value: 0.7821229050279331 and parameters: {'n_estimators': 73, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:35,285] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:35,715] Trial 34 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 72, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:36,149] Trial 35 finished with value: 0.7821229050279331 and parameters: {'n_estimators': 73, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:36,633] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:36,943] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 52, 'max_depth': 16}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:37,364] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:37,676] Trial 39 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 59, 'max_depth': 4}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:38,168] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 78, 'max_depth': 18}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:38,580] Trial 41 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 69, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:39,124] Trial 42 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 20}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:39,589] Trial 43 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 18}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:40,162] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 16}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:40,590] Trial 45 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 72, 'max_depth': 20}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:41,235] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 112, 'max_depth': 14}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:41,841] Trial 47 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 84, 'max_depth': 15}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:42,692] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 91, 'max_depth': 17}. Best is trial 32 with value: 0.7821229050279331.
[I 2026-03-17 10:02:43,271] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 19}. Best is trial 32 with value: 0.7821229050279331.

In [37]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279331
Best hyperparameters: {'n_estimators': 73, 'max_depth': 19}

In [38]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

## RandomizedSearchCV in Optuna

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [26]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-03-17 09:59:22,679] A new study created in memory with name: no-name-b7833ebb-8b13-46cd-90b8-eeb48c1abb66
[I 2026-03-17 09:59:25,594] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 185, 'max_depth': 15}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-03-17 09:59:26,928] Trial 1 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 17}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-03-17 09:59:28,142] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 70, 'max_depth': 11}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-03-17 09:59:29,036] Trial 3 finished with value: 0.756052141527002 and parameters: {'n_estimators': 93, 'max_depth': 3}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-03-17 09:59:29,980] Trial 4 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 106, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:30,558] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:30,825] Trial 6 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 54, 'max_depth': 3}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:31,736] Trial 7 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 164, 'max_depth': 10}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:32,552] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:33,166] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 107, 'max_depth': 17}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:33,505] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:34,122] Trial 11 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 110, 'max_depth': 9}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:35,080] Trial 12 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 192, 'max_depth': 4}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:35,686] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:36,250] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 99, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:36,797] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 106, 'max_depth': 4}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:37,301] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:37,712] Trial 17 finished with value: 0.750465549348231 and parameters: {'n_estimators': 85, 'max_depth': 3}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:38,715] Trial 18 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 143, 'max_depth': 4}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:39,265] Trial 19 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 62, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:40,744] Trial 20 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 171, 'max_depth': 5}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:41,232] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 8}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:42,092] Trial 22 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 171, 'max_depth': 4}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:43,004] Trial 23 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 192, 'max_depth': 3}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:43,950] Trial 24 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 170, 'max_depth': 8}. Best is trial 4 with value: 0.7783985102420857.
[I 2026-03-17 09:59:44,618] Trial 25 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 117, 'max_depth': 15}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:45,113] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 90, 'max_depth': 7}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:45,991] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 156, 'max_depth': 20}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:46,632] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 111, 'max_depth': 11}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:47,267] Trial 29 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 107, 'max_depth': 9}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:48,179] Trial 30 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 191, 'max_depth': 3}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:48,852] Trial 31 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 118, 'max_depth': 18}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:49,855] Trial 32 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 178, 'max_depth': 10}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:50,762] Trial 33 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 188, 'max_depth': 3}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:52,471] Trial 34 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 196, 'max_depth': 9}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:53,775] Trial 35 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 155, 'max_depth': 4}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:54,250] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 83, 'max_depth': 7}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:55,188] Trial 37 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 17}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:55,732] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 13}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:56,764] Trial 39 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 187, 'max_depth': 20}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:57,181] Trial 40 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 72, 'max_depth': 17}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:57,804] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 108, 'max_depth': 19}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:58,160] Trial 42 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 18}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:59,086] Trial 43 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 166, 'max_depth': 13}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 09:59:59,705] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 113, 'max_depth': 10}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 10:00:00,095] Trial 45 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 64, 'max_depth': 10}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 10:00:01,027] Trial 46 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 175, 'max_depth': 7}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 10:00:01,400] Trial 47 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 76, 'max_depth': 3}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 10:00:02,003] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 107, 'max_depth': 8}. Best is trial 25 with value: 0.7821229050279329.
[I 2026-03-17 10:00:02,357] Trial 49 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 63, 'max_depth': 10}. Best is trial 25 with value: 0.7821229050279329.

In [27]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 117, 'max_depth': 15}

In [28]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

# GridSearchCV in Optuna

In [29]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [30]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-03-17 10:01:17,353] A new study created in memory with name: no-name-d5d778d7-e650-4b5e-a8d8-041c6e94aaf9
[I 2026-03-17 10:01:18,435] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-17 10:01:20,358] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-17 10:01:20,928] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:22,013] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:23,293] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:23,863] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:25,021] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:25,875] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:26,735] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:28,397] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:30,113] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:31,269] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:32,364] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-17 10:01:32,641] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-17 10:01:33,244] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-17 10:01:33,581] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [31]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [32]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [39]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [40]:
# 1. Optimization History
plot_optimization_history(study).show()

In [41]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [42]:
# 3. Slice Plot
plot_slice(study).show()

In [43]:
# 4. Contour Plot
plot_contour(study).show()

In [44]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [45]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [53]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [54]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-03-17 10:26:04,966] A new study created in memory with name: no-name-5d4f00fd-8b99-417b-9fa7-4f99c53fcf9e
[I 2026-03-17 10:26:05,320] Trial 0 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 95.86423706827888, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.7858472998137801.
[I 2026-03-17 10:26:05,641] Trial 1 finished with value: 0.7597765363128491 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 53, 'learning_rate': 0.041605820491449896, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7858472998137801.
[I 2026-03-17 10:26:06,465] Trial 2 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 153, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 0 with value: 0.7858472998137801.
[I 2026-03-17 10:26:06,498] Trial 3 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 13.95477067788474, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7858472998137801.
[I 2026-03-17 10:26:06,986] Trial 4 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 94, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.7858472998137801.
[I 2026-03-17 10:26:10,868] Trial 5 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 299, 'learning_rate': 0.08054319463574318, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7858472998137801.
[I 2026-03-17 10:26:10,913] Trial 6 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3038592819733461, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 6 with value: 0.7858472998137803.
[I 2026-03-17 10:26:10,966] Trial 7 finished with value: 0.74487895716946 and parameters: {'classifier': 'SVM', 'C': 0.5338319869085317, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 6 with value: 0.7858472998137803.
[I 2026-03-17 10:26:12,827] Trial 8 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 257, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 6 with value: 0.7858472998137803.
[I 2026-03-17 10:26:17,092] Trial 9 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 296, 'learning_rate': 0.035373219294209356, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.7858472998137803.
[I 2026-03-17 10:26:17,125] Trial 10 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11197499489725579, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:17,154] Trial 11 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10319269294362379, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:17,184] Trial 12 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10155800167725569, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:17,221] Trial 13 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 1.2666625760248398, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:17,257] Trial 14 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 0.10306871663343384, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:17,308] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.668506692524965, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:17,340] Trial 16 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3728753547887118, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:17,378] Trial 17 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 1.5351804739636428, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:18,498] Trial 18 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 191, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:19,755] Trial 19 finished with value: 0.7597765363128491 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 198, 'learning_rate': 0.010330080383114117, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:19,788] Trial 20 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.201445949781552, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:19,819] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10528448639596727, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:19,853] Trial 22 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10209026641327408, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:19,888] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6931207212241336, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:19,920] Trial 24 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2384581701446516, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:19,951] Trial 25 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19237532867439128, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:20,039] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.514963814486217, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:21,913] Trial 27 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 133, 'learning_rate': 0.24576097543415615, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,187] Trial 28 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 229, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,227] Trial 29 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.8533772088449862, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,265] Trial 30 finished with value: 0.7597765363128492 and parameters: {'classifier': 'SVM', 'C': 0.1815342821080606, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,297] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10017320564954722, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,328] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10096383382545725, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,360] Trial 33 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3826179590440265, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,390] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17598843349812315, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:23,422] Trial 35 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.16442429535039335, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:24,232] Trial 36 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 107, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:26,101] Trial 37 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 56, 'learning_rate': 0.2880922297778838, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:26,154] Trial 38 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.35299284373349715, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:26,199] Trial 39 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1507314194270319, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:27,392] Trial 40 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 237, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:27,424] Trial 41 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1540035498960397, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:27,454] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16246038266202725, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:27,484] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2742896361738746, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:27,811] Trial 44 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 80.06737204388237, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:27,844] Trial 45 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14369805203380695, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:29,776] Trial 46 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 161, 'learning_rate': 0.011842187783230786, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:29,819] Trial 47 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.4865588561485832, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:29,855] Trial 48 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16072572155352305, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:29,900] Trial 49 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.930695846016492, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:29,941] Trial 50 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2569809640133025, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:29,973] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1409635819459629, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:30,007] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14769160539436646, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:30,041] Trial 53 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14539590937984873, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:30,075] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2709782793284303, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:30,112] Trial 55 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.4894472971006143, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:30,642] Trial 56 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 94, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:30,673] Trial 57 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1424976480069535, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:33,921] Trial 58 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 211, 'learning_rate': 0.11376591762943745, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:33,955] Trial 59 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 0.30932981322496167, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:33,989] Trial 60 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14075704259650515, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,021] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14098534261108842, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,052] Trial 62 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21033339345139487, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,084] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13336250340253827, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,115] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13330726641905594, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,144] Trial 65 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2216017055219947, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,176] Trial 66 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3408659690336011, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,221] Trial 67 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 8.7702531085525, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,437] Trial 68 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 51.93118902538472, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:34,472] Trial 69 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 0.6982403651728947, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:35,642] Trial 70 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 260, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:35,673] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13191631757463157, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:35,704] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21676391289499783, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:35,734] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13347895113687633, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:35,765] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12315150708505761, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:35,795] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.189573670727298, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:39,720] Trial 76 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 127, 'learning_rate': 0.024414031193514037, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:39,764] Trial 77 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.11189716458525813, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:39,796] Trial 78 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23011353279553382, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:39,833] Trial 79 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.41900174198718465, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:39,878] Trial 80 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.8086242194133322, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.
[I 2026-03-17 10:26:39,910] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15330217674367025, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 10 with value: 0.7895716945996275.

In [55]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.11197499489725579, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [57]:
from sklearn.metrics import accuracy_score

best_params = study.best_trial.params.copy()
best_params.pop("classifier")

# best_model = RandomForestClassifier(**best_params, random_state=42)
best_model = SVC(**best_params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [58]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.785847,2026-03-17 10:26:04.968532,2026-03-17 10:26:05.320345,0 days 00:00:00.351813,95.864237,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.759777,2026-03-17 10:26:05.321350,2026-03-17 10:26:05.641682,0 days 00:00:00.320332,NaN,NaN,GradientBoosting,NaN,NaN,0.041606,3.0,1.0,2.0,53.0,COMPLETE
2,2,0.756052,2026-03-17 10:26:05.642839,2026-03-17 10:26:06.465842,0 days 00:00:00.823003,NaN,True,RandomForest,NaN,NaN,NaN,7.0,8.0,3.0,153.0,COMPLETE
3,3,0.692737,2026-03-17 10:26:06.467045,2026-03-17 10:26:06.498047,0 days 00:00:00.031002,13.954771,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.763501,2026-03-17 10:26:06.499084,2026-03-17 10:26:06.986345,0 days 00:00:00.487261,NaN,False,RandomForest,NaN,NaN,NaN,15.0,3.0,4.0,94.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.709497,2026-03-17 10:26:44.517937,2026-03-17 10:26:44.550881,0 days 00:00:00.032944,0.116640,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.785847,2026-03-17 10:26:44.552829,2026-03-17 10:26:44.584702,0 days 00:00:00.031873,0.208179,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.698324,2026-03-17 10:26:44.585937,2026-03-17 10:26:44.625101,0 days 00:00:00.039164,26.022871,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2026-03-17 10:26:44.626093,2026-03-17 10:26:44.657397,0 days 00:00:00.031304,0.142261,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.785847,2026-03-17 10:26:44.658464,2026-03-17 10:26:44.687969,0 days 00:00:00.029505,0.255777,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [59]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 80
GradientBoosting    10
RandomForest        10
Name: count, dtype: int64

In [60]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.751397
RandomForest        0.765922
SVM                 0.776094
Name: value, dtype: float64

In [61]:
# 1. Optimization History
plot_optimization_history(study).show()

In [62]:
# 3. Slice Plot
plot_slice(study).show()

In [63]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()